spring:
  config:
    import: optional:file:.env
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ID}
    password: ${EMAIL_PW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:mem:knitly;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: never
frontend:
  url: http://dummy-test-frontend.com

  # Redis 설정 (테스트용 Embedded Redis 또는 로컬 Redis)
  data:
    redis:
      host: localhost
      port: 6379

custom:
  jwt:
    # application.yml을 참고하여 가짜 시크릿 키 제공
    secretKey: "dGVzdC1zZWNyZXQta2V5LXRlc3Qtc2VjcmV0LWtleQo="
    accessTokenExpireSeconds: 1800  # 30분
    refreshTokenExpireSeconds: 604800  # 7일

# --- 3. Actuator 상태 점검 설정 ---
management:
  health:
    # (핵심!) 테스트 시 불필요한 메일 서버 상태 점검 비활성화
    mail:
      enabled: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

#spring:
#  datasource:
#    url: jdbc:h2:mem:knitly;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    #show-sql: true
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
#  sql:
#    init:
#      mode: never
#
#logging:
#  level:
#    root: INFO
#    com.mysite.knitly: DEBUG
#    org.hibernate.SQL: INFO
#    org.springframework.transaction.interceptor: INFO
##    org.hibernate.orm.jdbc.bind: trace
#
#frontend:
#  url: http://localhost:3000